### ISSUE TITLE
Possibility to categorize by receiver account id

### ISSUE THREAD

**Issue by KonstantinTyukalov** [AlexanderMakarov/am-budget-view#4]
Hi! 
I would like to categorize some transactions by the `<Receiver-PayerAccount/>` prop in the Inecobank statement.
Is there any plans to support other fields instead of `<Details>`?
If so - I'm open to contribute.
Thanks

**Comment by AlexanderMakarov** [comment]
Hi Konstantin! It is the exact feature [I am working on right now](https://github.com/AlexanderMakarov/am-budget-view/commits/new_config/) :smile: 

Unfortunately it requires to change configuration format. Also assigning account numbers in YAML may be very tedious and error prone so I am implementing a simple UI for categorization configuration. ~40% of work done for today. Thank you for the extra reason to complete it soon :hugs:

**Comment by AlexanderMakarov** [comment]
FYI: relevant changes were added to ["new_config" branch](https://github.com/AlexanderMakarov/am-budget-view/commits/new_config/) so you may use them (like via `make run`) but I need to some time to prepare a release. It requires more testing and documentation updates.

Most probably it would be 2.0 version.

**Comment by AlexanderMakarov** [comment]
Implemented here https://github.com/AlexanderMakarov/am-budget-view/releases/tag/release2.0.0
